services:
  db:
    image: postgres
  alpine:
    image: mcr.microsoft.com/devcontainers/base:alpine-3.20
    tty: true
    stdin_open: true
    environment:
      MY_DATABSE_HOST: "db:5432"
    volumes:
      - ..:/workspace
